config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  root "static_pages#index"

  get "age_verification", to: "age_verification#new"
  post "age_verification", to: "age_verification#create"
  get "search", to: "search#index"
  get "menu", to: "menus#index"
  get "main", to: "main_pages#index"

  resources :age_verification, only: [ :create ] # age_verificationsのルートを定義
  resources :posts, only: [:index, :new, :create, :destroy, :show, :edit, :update]
  resources :users, only: [:destroy, :edit, :update, :show]


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  # Association
  belongs_to :user

  # Validation
  validates :title, presence: true
  validates :sake_name, presence: true
  validates :taste_rating, presence: true, inclusion: { in: 1..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Association
  has_many :posts, dependent: :destroy

  # Validation
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
end

app/controllers/age_verification_controller.rb
class AgeVerificationController < ApplicationController
  # def show
  # end

  # def verify
  #   if params[:age] == "yes"
  #     redirect_to new_user_registration_path
  #   else
  #     redirect_to root_path, alert: "20歳以上でなければ登録できません。"
  #   end
  # end

  def new
    # 年齢確認ページを表示
  end

  def create
    if params[:age_confirmation] == "yes"
      redirect_to new_user_registration_path # Yesを選んだ場合、新規登録ページに遷移
    else
      redirect_to root_path, alert: "20歳以上の方のみご利用いただけます。" # Noを選んだ場合、ホームにリダイレクト
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end

  # ログインやサインアップ後のリダイレクト先を指定
  def after_sign_in_path_for(resource)
    main_path # メインページのパスに変更
  end

  # サインアップ後のリダイレクト先を指定
  def after_sign_up_path_for(resource)
    main_path # メインページのパスに変更
  end
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  before_action :authenticate_user! # ログインしているユーザーのみアクセス可能

  # def show
  # end

  def index
    @posts = Post.all.order(created_at: :desc) # 投稿を作成日時でソートして一覧表示
  end

  # メニューページの表示（例: ログイン後のユーザーに特定の機能を提供する）
  def menu
    # メニューページはログインしたユーザーのみアクセス可能
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_posts = current_user.posts # ユーザーの投稿を取得
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]


  # 投稿一覧ページ（メインページ）の表示
  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  # 新規投稿作成ページの表示
  def new
    @post = Post.new
  end

  # 投稿の保存処理
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to main_path, notice: "投稿が作成されました。"
    else
      flash.now[:alert] = "すべてのフィールドを入力してください。"
      render :new
    end
  end

  # 投稿の詳細を表示
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    # 編集用のフォームを表示するためのアクション
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: '投稿が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      flash[:notice] = '投稿が削除されました。'
      redirect_to main_path # メインページにリダイレクト
    else
      flash[:alert] = '削除権限がありません。'
      redirect_to post_path(@post)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user!
    redirect_to posts_path, alert: '権限がありません。' unless current_user == @post.user
  end
  
  def post_params
    params.require(:post).permit(:title, :sake_name, :taste_rating)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # skip_before_action :require_no_authentication, only: [ :new, :create ]

  # def create
  #   super
  # end

  def new
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @posts = Post.includes(:user) # ユーザーデータを含めて投稿を取得

    # 各フィールドに対してあいまい検索を行う
    if params[:title].present? || params[:sake_name].present? || params[:username].present?
      @posts = @posts.joins(:user) # ユーザーと結合

      # titleに対する検索条件
      if params[:title].present?
        @posts = @posts.where("title ILIKE ?", "%#{params[:title]}%")
      end

      # sake_nameに対する検索条件
      if params[:sake_name].present?
        @posts = @posts.where("sake_name ILIKE ?", "%#{params[:sake_name]}%")
      end

      # usernameに対する検索条件
      if params[:username].present?
        @posts = @posts.where("users.username ILIKE ?", "%#{params[:username]}%")
      end
    end

      @hit_count = @posts.count # ヒット数をカウント
  
      @posts = @posts.order(created_at: :desc) # 投稿を新しい順に並べる
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  # ログインページにアクセスする前に実行されるアクション
  prepend_before_action :check_logged_in, only: [ :new ]

  def new
    super
  end

  def create
    super do |user|
      if user_signed_in?
        return redirect_to main_path # ログインが成功したらmain_pageに遷移し、処理を終了
      end
    end
  end

  private

  def check_logged_in
    # すでにログインしている場合、ログアウトしてから再度ログインページに遷移
    if user_signed_in?
      sign_out(current_user)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:top, :age_verification]

  # def top
  # end

  # def age_verification
  #   # 年齢確認ページの処理
  # end

  # def new_user_registration
  #   # 新規登録ページの処理
  # end

  # def new_user_session
  #   # ログインページの処理
  # end

  # def main
  #   # メインページの処理
  # end


  def index
    # ホームページを表示するアクション
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_user, only: [:destroy]

  def show
    @user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to menus_path, notice: 'アカウント情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    if @user == current_user
      @user.destroy
      flash[:notice] = 'アカウントが削除されました。'
      redirect_to root_path # static_pageにリダイレクト
    else
      flash[:alert] = '削除権限がありません。'
      redirect_to edit_user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  protected

  # Deviseにカスタムパラメーターを許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/age_verification/new.html.erb
<h1>20歳以上ですか？</h1>
<%= form_with url: age_verification_path, method: :post do %>
  <%= submit_tag 'はい', name: 'age_confirmation', value: 'yes', class: 'btn btn-success' %>
  <%= submit_tag 'いいえ', name: 'age_confirmation', value: 'no', class: 'btn btn-danger' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_pages/index.html.erb
<div class="header">
  <h1>日本酒いかが</h1>
  <%= form_with url: search_path, method: :get, local: true, class: "flex items-center space-x-2" do |form| %>
    <div>
      <label for="title">タイトル:</label>
      <%= text_field_tag :title, params[:title], placeholder: "タイトルで検索" %>
    </div>

    <div>
      <label for="sake_name">銘柄:</label>
      <%= text_field_tag :sake_name, params[:sake_name], placeholder: "銘柄で検索" %>
    </div>

    <div>
      <label for="username">ユーザーネーム:</label>
      <%= text_field_tag :username, params[:username], placeholder: "ユーザーネームで検索" %>
    </div>

    <div>
      <%= form.submit "検索", class: "bg-blue-500 text-white p-2 rounded" %>
    </div>
    <p>ログイン中: <%= current_user.username %></p>
  <% end %>
</div>

<div class="sidebar">
  <%= link_to '新規投稿', new_post_path %>
  <%= link_to 'メニュー', menu_path %>
</div>

<div class="content">
  <h2>投稿一覧</h2>
  <% @posts.each do |post| %>
    <div>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <p>投稿者: <%= post.user.username %></p>
      <p>投稿日: <%= post.created_at.strftime('%Y-%m-%d') %></p>
    </div>
  <% end %>
</div>

app/views/menus/index.html.erb
<div class="header">
  <h1>メニュー</h1>
  <p>ログイン中のユーザー: <%= current_user.username if user_signed_in? %></p>
</div>

<div class="sidebar">
  <%= link_to 'ユーザー情報変更', edit_user_path(current_user), class: 'btn btn-primary' %>
  <%= link_to '投稿一覧へ', main_path %>
</div>

<div class="content">
  <h2>あなたの投稿一覧</h2>
  <% @user_posts.each do |post| %>
    <div>
      <h3><%= link_to post.title, post_path(post) %></h3>
      <p>銘柄: <%= post.sake_name %></p>
      <p>投稿日: <%= post.created_at.strftime('%Y-%m-%d') %></p>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="header">
  <h1>日本酒いかが</h1>
  <%= link_to '投稿一覧へ', posts_path %>
</div>

<div class="content">
  <h2>投稿を編集</h2>
  <%= form_with(model: @post, local: true) do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "エラー") %>が発生しました:</h2>
        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title, class: "input input-bordered border-black w-full" %>
    </div>

    <div>
      <%= form.label :sake_name, "銘柄" %>
      <%= form.text_field :sake_name, class: "input input-bordered border-black w-full" %>
    </div>

    <div>
      <%= form.label :taste_rating, "口当たり (1-5)" %>
      <div class="rating rating-lg flex items-center">
        <%= form.radio_button :taste_rating, 1, class: "rating-hidden" %>
        <%= form.radio_button :taste_rating, 2, class: "mask mask-star-2" %>
        <%= form.radio_button :taste_rating, 3, class: "mask mask-star-2" %>
        <%= form.radio_button :taste_rating, 4, class: "mask mask-star-2" %>
        <%= form.radio_button :taste_rating, 5, class: "mask mask-star-2" %>
      </div>
    </div>

    <div>
      <%= form.submit "更新", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2>新規投稿</h2>
<%= form_with(model: @post, local: true) do |f| %>
  <div class="flex flex-col space-y-4">
    <div class="card bg-base-300 rounded-box">
      <div class="p-4">
        <%= f.label :title, "タイトル" %>
        <%= f.text_field :title, class: "input input-bordered border-black w-full" %>
      </div>
    </div>

    <div class="divider"></div>

    <div class="card bg-base-300 rounded-box">
      <div class="p-4">
        <%= f.label :sake_name, "銘柄" %>
        <%= f.text_field :sake_name, class: "input input-bordered border-black w-full" %>
      </div>
    </div>

    <div class="divider"></div>

    <div class="card bg-base-300 rounded-box">
      <div class="p-4">
        <%= f.label :taste_rating, "口当たり (1-5)", class: "text-xl font-bold" %>
        <div class="rating rating-lg flex items-center overflow-x-auto"> <!-- overflow-x-autoを追加 -->
          <%= f.radio_button :taste_rating, 1, class: "rating-hidden" %>
          <%= f.radio_button :taste_rating, 2, class: "mask mask-star-2" %>
          <%= f.radio_button :taste_rating, 3, class: "mask mask-star-2" %>
          <%= f.radio_button :taste_rating, 4, class: "mask mask-star-2" %>
          <%= f.radio_button :taste_rating, 5, class: "mask mask-star-2" %>
        </div>
        <div class="flex justify-between mt-2">
          <span>甘口</span>
          <span>辛口</span>
        </div>
      </div>
    </div>

    <div class="flex space-x-2 mt-4">
      <%= f.submit "投稿する", class: "btn btn-primary" %>
      <%= link_to "キャンセル", main_path, class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="header">
  <h1>日本酒いかが</h1>
  <%= form_with url: search_path, method: :get, local: true, class: "flex items-center space-x-2" do |form| %>
    <div>
      <label for="title">タイトル:</label>
      <%= text_field_tag :title, params[:title], placeholder: "タイトルで検索" %>
    </div>

    <div>
      <label for="sake_name">銘柄:</label>
      <%= text_field_tag :sake_name, params[:sake_name], placeholder: "銘柄で検索" %>
    </div>

    <div>
      <label for="username">ユーザーネーム:</label>
      <%= text_field_tag :username, params[:username], placeholder: "ユーザーネームで検索" %>
    </div>

    <div>
      <%= form.submit "検索", class: "bg-blue-500 text-white p-2 rounded" %>
    </div>
    <p>ログイン中: <%= current_user.username %></p>
  <% end %>
</div>

<div class="sidebar">
  <%= link_to '投稿一覧へ', main_path %>
  <%= link_to '新規投稿', new_post_path %>
  <%= link_to 'メニュー', menu_path %>
</div>

<div class="content">
  <h1><%= @post.title %></h1>
  <p><strong>銘柄:</strong> <%= @post.sake_name %></p>
  <p><strong>口当たり:</strong></p>
  <div class="rating rating-lg flex items-center">
    <% (1..5).each do |value| %>
      <%= radio_button_tag "taste_rating", value, @post.taste_rating == value, class: "mask mask-star-2", disabled: true %>
    <% end %>
  </div>
  <p><strong>投稿者 by:</strong> <%= @post.user.username %></p>
  <p><strong>投稿日 at:</strong> <%= @post.created_at.strftime('%B %d, %Y') %></p>

  <%= link_to '編集する', edit_post_path(@post), class: 'btn btn-primary' if current_user == @post.user %>
  <%= button_to '削除する', post_path(@post), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' if current_user == @post.user %>
</div>

app/views/search/index.html.erb
<h1>検索結果</h1>
<p>該当 <%= @posts.count %> 件:</p>

<% @posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p>銘柄: <%= post.sake_name %></p>
    <p>投稿者: <%= post.user.username %></p>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2019. RUNTEQ</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
       <%# image_tag 'logo.png' %>
    <% end %>
    <button class='navbar-toggler' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent'
      aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
      <ul class='navbar-nav ms-auto main-nav align-items-center'>
        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '掲示板', '#', class: 'nav-link dropdown-toggle', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-board-menu' %>
          <div class='dropdown-menu dropdown-menu-end'>
            <%= link_to '掲示板一覧', '#', class: 'dropdown-item' %>
            <%= link_to '掲示板作成', '#', class: 'dropdown-item' %>
          </div>
        </li>

        <li class='nav-item'>
          <%= link_to 'ブックマーク一覧', '#', class: 'nav-link' %>
        </li>

        <li class='nav-item dropdown dropdown-slide'>
          <%= link_to '#', class: 'nav-link', data: { bs_toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' }, id: 'header-profile' do %>
            <%# image_tag 'sample.jpg', class: 'rounded-circle mr15', width: '40', height: '40' %>
          <% end %>
          <div class='dropdown-menu dropdown-menu-end'>
            <div class='dropdown-item'>らんてっく たろう</div>
            <div class='dropdown-divider'></div>
            <%= link_to 'プロフィール', '#', class: 'dropdown-item' %>
            <%= link_to 'ログアウト', '#', class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/static_pages/index.erb
<div class="flex flex-col items-center p-8 bg-base-100 rounded-lg shadow-md" data-theme="business">
  <h1 class="text-3xl font-bold mb-4">日本酒いかが</h1>
  <p class="text-lg text-gray-600 mb-6">このアプリは日本酒の評価やレビューを投稿できるアプリです。</p>
  <div class="flex space-x-4">
    <button class="btn btn-primary" onclick="location.href='<%= age_verification_path %>'">サインアップ</button>
    <button class="btn btn-secondary" onclick="location.href='<%= new_user_session_path %>'">ログイン</button>
  </div>
</div>

app/views/users/edit.html.erb
<h1>ユーザー情報の変更</h1>

<%= form_with model: current_user, local: true do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
  <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "off" %>
    <small>(空白の場合は変更されません)</small>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div>
    <%= form.submit "更新", class: "bg-blue-500 text-white p-2 rounded" %>
  </div>

  <div>
    <%= link_to 'アカウントを削除', user_path(current_user), method: :delete, data: { confirm: '本当にアカウントを削除しますか？' }, class: "btn btn-danger" %>
  </div>

  <div class="mt-4">
    <%= link_to 'メインページに戻る', main_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div>
  <%= form_with url: user_path(current_user), method: :delete, local: true do %>
    <button type="submit" class="btn btn-danger">アカウントを削除</button>
  <% end %>
</div>